ARG DLIB_SOURCE_IMAGE=registry.hub.docker.com/library/ubuntu:jammy
ARG DLIB_BUILD_FLAVOR=default

### minimal image ###
FROM "$DLIB_SOURCE_IMAGE" as flavor-minimal

# Remove Docker customizations
RUN rm -rf /etc/apt/apt.conf.d/docker-*

# Notes:
# - grub-pc and grub-efi-amd64 conflicts
RUN apt-get update -y \
    && apt-get install -y linux-generic initramfs-tools grub-pc grub-efi-amd64-bin efibootmgr shim-signed mokutil systemd kmod locales \
    && rm -rf /var/lib/apt/lists/*

### default image ###
FROM flavor-minimal as flavor-default

RUN apt-get update -y \
    && apt-get install -y qemu-guest-agent cloud-init openssh-server openssh-client vim mtr-tiny \
    && rm -rf /var/lib/apt/lists/*

### finalize ###
FROM "flavor-$DLIB_BUILD_FLAVOR"

RUN passwd -d root
