ARG BOOTABLE_SOURCE_IMAGE=registry.hub.docker.com/library/alpine:edge
ARG BOOTABLE_BUILD_FLAVOR=default

### minimal image ###
FROM "$BOOTABLE_SOURCE_IMAGE" as flavor-minimal

RUN apk add --no-cache --update linux-lts linux-firmware mkinitfs amd-ucode intel-ucode grub-efi grub-bios efibootmgr mokutil \
    && rm -rf /var/cache/pacman/pkg/*

### default image ###
FROM flavor-minimal as flavor-default

### finalize ###
FROM "flavor-$BOOTABLE_BUILD_FLAVOR"

# TODO: fix timezone info
RUN passwd -d root
