ARG DLIB_SOURCE_IMAGE=registry.hub.docker.com/library/debian:bookworm-slim
ARG DLIB_BUILD_FLAVOR=default

### minimal image ###
FROM "$DLIB_SOURCE_IMAGE" as flavor-minimal

# Remove Docker customizations
RUN rm -rf /etc/apt/apt.conf.d/docker-*

# TODO: refactor this with release detection
# Add repository components (Debian 11 and earlier)
RUN [ -f /etc/apt/sources.list ] && sed -Ei'' 's/main$/main contrib non-free/g' /etc/apt/sources.list || true
# Add repository components (deb822 style; Debian 12 and later)
RUN [ -f /etc/apt/sources.list.d/debian.sources ] && sed -Ei'' 's/^Components: .*$/Components: main contrib non-free non-free-firmware/g' /etc/apt/sources.list.d/debian.sources || true

# Notes:
# - grub-efi-amd64 and grub-pc conflict with each other; install *-bin works https://askubuntu.com/a/1253218; grub-cloud-amd64 does this automatically for us
RUN apt-get update -y \
    && apt-get install -y linux-image-amd64 firmware-linux-nonfree initramfs-tools grub-cloud-amd64 efibootmgr shim-signed mokutil systemd kmod locales \
    && rm -rf /var/lib/apt/lists/*

### default image ###
FROM flavor-minimal as flavor-default

RUN apt-get update -y \
    && apt-get install -y qemu-guest-agent cloud-init openssh-server openssh-client vim mtr-tiny \
    && rm -rf /var/lib/apt/lists/*

### finalize ###
FROM "flavor-$DLIB_BUILD_FLAVOR"

RUN passwd -d root
