ARG BOOTABLE_SOURCE_IMAGE=docker.io/library/centos:8
FROM "$BOOTABLE_SOURCE_IMAGE"
LABEL bootable.distro.like="rhel"
LABEL bootable.distro.like-version="8"
LABEL bootable.plugin.partition="gpt"
LABEL bootable.plugin.bootloader="grub2"
LABEL bootable.plugin.initrd="dracut"

RUN dnf -y install kernel dracut grub2-efi-x64 grub2-efi-x64-modules grub2-pc grub2-pc-modules shim-x64 systemd \
    && dnf clean all
