ARG BOOTABLE_SOURCE_IMAGE=registry.hub.docker.com/library/fedora:rawhide
ARG BOOTABLE_BUILD_FLAVOR=default

### minimal image ###
FROM "$BOOTABLE_SOURCE_IMAGE" as flavor-minimal

# Notes:
# - `grub2-efi` and `grub2-efi-modules` might install arm64 versions for you; let's be explicit about the architecture
# - `fedora-release-identity-container` need to be replaced so we does not identify as a container image
RUN dnf -y install --allowerasing fedora-release-identity-server \
    && dnf -y install kernel dracut grub2-efi-x64 grub2-efi-x64-modules grub2-pc grub2-pc-modules shim-x64 passwd systemd ca-certificates \
    && dnf clean all

### default image ###
FROM flavor-minimal as flavor-default

RUN dnf -y install qemu-guest-agent cloud-init openssh vim mtr \
    && dnf clean all

### finalize ###
FROM "flavor-$BOOTABLE_BUILD_FLAVOR"

RUN passwd -d root
