ARG DLIB_SOURCE_IMAGE=registry.hub.docker.com/library/archlinux:base
ARG DLIB_BUILD_FLAVOR=default

### minimal image ###
FROM "$DLIB_SOURCE_IMAGE" as flavor-minimal

# fix polkit permission problem on the default archlinux docker image
RUN chmod 755 /usr/share/polkit-1/rules.d \
    && chmod 755 /var/log/audit

RUN pacman -Syu --noconfirm \
    && pacman -S --noconfirm base linux linux-firmware mkinitcpio amd-ucode intel-ucode grub efibootmgr \
    && rm -rf /var/cache/pacman/pkg/*

### default image ###
FROM flavor-minimal as flavor-default

RUN pacman -Syu --noconfirm \
    && pacman -S --noconfirm qemu-guest-agent vim \
    && rm -rf /var/cache/pacman/pkg/*

### finalize ###
FROM "flavor-$DLIB_BUILD_FLAVOR"

RUN passwd -d root
