ARG BOOTABLE_SOURCE_IMAGE=registry.hub.docker.com/library/centos:6
ARG BOOTABLE_BUILD_FLAVOR=default

### minimal image ###
FROM "$BOOTABLE_SOURCE_IMAGE" as flavor-minimal

# switch to vault.centos.org
RUN sed -Ei'' 's/mirror.centos.org/vault.centos.org/g; s/#baseurl=/baseurl=/g; s/mirrorlist=/#mirrorlist=/g' /etc/yum.repos.d/*.repo

RUN yum -y --setopt=skip_missing_names_on_install=False install kernel dracut grub grubby sysvinit ca-certificates \
    && yum clean all

### default image ###
FROM flavor-minimal as flavor-default

RUN yum -y --setopt=skip_missing_names_on_install=False install NetworkManager qemu-guest-agent cloud-init openssh vim mtr \
    && yum clean all

### finalize ###
FROM "flavor-$BOOTABLE_BUILD_FLAVOR"

RUN passwd -d root
