name: "Build base images"

on:
  push:
    branches:
      - "trunk"
  schedule:
    - cron: "0 4 * * *"

jobs:
  toolchain:
    name: "Toolchain"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: "./create_toolchain_image.sh"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: "docker push docker.io/jamesits/bootable:toolchain-latest"

  images:
    name: "Image"
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: ["toolchain"]
    strategy:
      matrix:
        distro:
          - "almalinux/8"
          - "almalinux/9"
          - "alpinelinux/edge"
          - "archlinux/rolling"
          - "centos/7"
          - "centos/8"
          - "debian/buster"
          - "debian/bullseye"
          - "debian/bookworm"
          - "debian/trixie"
          - "debian/sid"
          - "fedora/38"
          - "fedora/39"
          - "fedora/40"
          - "fedora/rawhide"
          - "rockylinux/8"
          - "rockylinux/9"
          - "ubuntu/bionic"
          - "ubuntu/focal"
          - "ubuntu/jammy"
          - "ubuntu/noble"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          ./create_base_image.sh "${{ matrix.distro }}" "jamesits/bootable:base-${${{ matrix.distro }}//\//-}-grub2-latest" "grub2"
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: |
          docker push "docker.io/jamesits/bootable:base-${${{ matrix.distro }}//\//-}-grub2-latest"
